from __future__ import annotations


def pick_texts(texts_map: dict[str, dict[str, str]], language: str) -> dict[str, str]:
    return texts_map.get(language, texts_map["es"])


def get_dialog_texts(section: str, language: str) -> dict[str, str]:
    return pick_texts(DIALOG_TEXTS[section], language)


def get_menu_texts(section: str, language: str) -> dict[str, str]:
    return pick_texts(MENU_TEXTS[section], language)


def get_toolbar_texts(language: str) -> dict[str, str]:
    return pick_texts(TOOLBAR_TEXTS, language)


def get_sidebar_texts(language: str) -> dict[str, str]:
    return pick_texts(SIDEBAR_TEXTS, language)


def get_help_changes(language: str) -> list[str]:
    return HELP_CHANGES.get(language, HELP_CHANGES["es"])


MENU_TEXTS = {
    "file": {
        "es": {
            "label": "Archivo",
            "new": "Nueva",
            "new_from_template": "Nueva desde plantilla",
            "new_quick_note": "Nota rapida",
            "new_meeting": "Reunion (agenda)",
            "new_todo": "Pendientes (To-Do)",
            "new_journal": "Diario",
            "save": "Guardar",
            "delete": "Borrar",
            "export_txt": "Exportar .txt",
            "export_md": "Exportar .md",
            "import_md": "Importar .md",
            "exit": "Salir",
        },
        "en": {
            "label": "File",
            "new": "New",
            "new_from_template": "New from template",
            "new_quick_note": "Quick note",
            "new_meeting": "Meeting (agenda)",
            "new_todo": "To-Do",
            "new_journal": "Journal",
            "save": "Save",
            "delete": "Delete",
            "export_txt": "Export .txt",
            "export_md": "Export .md",
            "import_md": "Import .md",
            "exit": "Exit",
        },
        "pt": {
            "label": "Arquivo",
            "new": "Nova",
            "new_from_template": "Nova por modelo",
            "new_quick_note": "Nota rapida",
            "new_meeting": "Reuniao (agenda)",
            "new_todo": "Pendentes (To-Do)",
            "new_journal": "Diario",
            "save": "Salvar",
            "delete": "Excluir",
            "export_txt": "Exportar .txt",
            "export_md": "Exportar .md",
            "import_md": "Importar .md",
            "exit": "Sair",
        },
        "fr": {
            "label": "Fichier",
            "new": "Nouveau",
            "new_from_template": "Nouveau depuis modele",
            "new_quick_note": "Note rapide",
            "new_meeting": "Reunion (agenda)",
            "new_todo": "A faire (To-Do)",
            "new_journal": "Journal",
            "save": "Enregistrer",
            "delete": "Supprimer",
            "export_txt": "Exporter .txt",
            "export_md": "Exporter .md",
            "import_md": "Importer .md",
            "exit": "Quitter",
        },
    },
    "edit": {
        "es": {
            "label": "Editar",
            "undo": "Deshacer",
            "redo": "Rehacer",
            "cut": "Cortar",
            "copy": "Copiar",
            "paste": "Pegar",
            "delete": "Borrar seleccion",
            "select_all": "Seleccionar todo",
            "select_line": "Seleccionar linea",
            "select_word": "Seleccionar palabra",
        },
        "en": {
            "label": "Edit",
            "undo": "Undo",
            "redo": "Redo",
            "cut": "Cut",
            "copy": "Copy",
            "paste": "Paste",
            "delete": "Delete selection",
            "select_all": "Select all",
            "select_line": "Select line",
            "select_word": "Select word",
        },
        "pt": {
            "label": "Editar",
            "undo": "Desfazer",
            "redo": "Refazer",
            "cut": "Cortar",
            "copy": "Copiar",
            "paste": "Colar",
            "delete": "Excluir selecao",
            "select_all": "Selecionar tudo",
            "select_line": "Selecionar linha",
            "select_word": "Selecionar palavra",
        },
        "fr": {
            "label": "Edition",
            "undo": "Annuler",
            "redo": "Retablir",
            "cut": "Couper",
            "copy": "Copier",
            "paste": "Coller",
            "delete": "Supprimer selection",
            "select_all": "Tout selectionner",
            "select_line": "Selectionner ligne",
            "select_word": "Selectionner mot",
        },
    },
    "search": {
        "es": {
            "label": "Buscar",
            "list": "Buscar en lista",
            "note": "Buscar en nota...",
            "next": "Buscar siguiente",
            "match_case": "Coincidir mayusculas",
            "regex": "Regex",
            "whole_word": "Palabra completa",
            "replace_menu": "Reemplazar...",
            "last_search": "Ultima busqueda: {term}",
            "last_search_empty": "-",
            "find_title": "Buscar",
            "find_label": "Texto a buscar:",
            "replace_label": "Reemplazar con:",
            "replace_one": "Reemplazar uno",
            "replace_all": "Reemplazar todo",
            "replace_confirm": "Reemplazar todas las coincidencias?",
            "replace_done": "Reemplazos: {count}",
            "prev": "Buscar anterior",
        },
        "en": {
            "label": "Search",
            "list": "Search in list",
            "note": "Find in note...",
            "next": "Find next",
            "match_case": "Match case",
            "regex": "Regex",
            "whole_word": "Whole word",
            "replace_menu": "Replace...",
            "last_search": "Last search: {term}",
            "last_search_empty": "-",
            "find_title": "Find",
            "find_label": "Find:",
            "replace_label": "Replace with:",
            "replace_one": "Replace one",
            "replace_all": "Replace all",
            "replace_confirm": "Replace all matches?",
            "replace_done": "Replacements: {count}",
            "prev": "Find previous",
        },
        "pt": {
            "label": "Buscar",
            "list": "Buscar na lista",
            "note": "Buscar na nota...",
            "next": "Buscar seguinte",
            "match_case": "Diferenciar maiusculas",
            "regex": "Regex",
            "whole_word": "Palavra inteira",
            "replace_menu": "Substituir...",
            "last_search": "Ultima busca: {term}",
            "last_search_empty": "-",
            "find_title": "Buscar",
            "find_label": "Texto a buscar:",
            "replace_label": "Substituir por:",
            "replace_one": "Substituir um",
            "replace_all": "Substituir todos",
            "replace_confirm": "Substituir todas as ocorrencias?",
            "replace_done": "Substituicoes: {count}",
            "prev": "Buscar anterior",
        },
        "fr": {
            "label": "Rechercher",
            "list": "Rechercher dans la liste",
            "note": "Rechercher dans la note...",
            "next": "Rechercher suivant",
            "match_case": "Respecter la casse",
            "regex": "Regex",
            "whole_word": "Mot entier",
            "replace_menu": "Remplacer...",
            "last_search": "Derniere recherche: {term}",
            "last_search_empty": "-",
            "find_title": "Rechercher",
            "find_label": "Texte a rechercher:",
            "replace_label": "Remplacer par:",
            "replace_one": "Remplacer un",
            "replace_all": "Tout remplacer",
            "replace_confirm": "Remplacer toutes les occurrences?",
            "replace_done": "Remplacements: {count}",
            "prev": "Rechercher precedent",
        },
    },
    "format": {
        "es": {
            "label": "Formato",
            "bold": "Negrita",
            "italic": "Cursiva",
            "underline": "Subrayado",
            "strike": "Tachado",
            "font_menu": "Fuente",
            "color_menu": "Color",
            "font": "Fuente...",
            "size_plus": "Tamano +",
            "size_minus": "Tamano -",
            "size_reset": "Restablecer tamano",
            "text_color": "Color de texto...",
            "bg_color": "Color de fondo...",
            "clear_sel": "Limpiar formato (seleccion)",
            "reset": "Restablecer formato",
        },
        "en": {
            "label": "Format",
            "bold": "Bold",
            "italic": "Italic",
            "underline": "Underline",
            "strike": "Strikethrough",
            "font_menu": "Font",
            "color_menu": "Color",
            "font": "Font...",
            "size_plus": "Size +",
            "size_minus": "Size -",
            "size_reset": "Reset size",
            "text_color": "Text color...",
            "bg_color": "Background color...",
            "clear_sel": "Clear formatting (selection)",
            "reset": "Reset formatting",
        },
        "pt": {
            "label": "Formato",
            "bold": "Negrito",
            "italic": "Italico",
            "underline": "Sublinhado",
            "strike": "Riscado",
            "font_menu": "Fonte",
            "color_menu": "Cor",
            "font": "Fonte...",
            "size_plus": "Tamanho +",
            "size_minus": "Tamanho -",
            "size_reset": "Redefinir tamanho",
            "text_color": "Cor do texto...",
            "bg_color": "Cor de fundo...",
            "clear_sel": "Limpar formato (selecao)",
            "reset": "Redefinir formato",
        },
        "fr": {
            "label": "Format",
            "bold": "Gras",
            "italic": "Italique",
            "underline": "Souligner",
            "strike": "Barre",
            "font_menu": "Police",
            "color_menu": "Couleur",
            "font": "Police...",
            "size_plus": "Taille +",
            "size_minus": "Taille -",
            "size_reset": "Reinitialiser taille",
            "text_color": "Couleur du texte...",
            "bg_color": "Couleur de fond...",
            "clear_sel": "Effacer format (selection)",
            "reset": "Reinitialiser format",
        },
    },
    "view": {
        "es": {
            "label": "Ver",
            "zoom": "Zoom",
            "zoom_in": "Acercar",
            "zoom_out": "Alejar",
            "zoom_reset": "Restaurar zoom",
            "reset_view": "Restablecer vista",
            "zoom_label": "Zoom: {percent}%",
            "wrap": "Ajuste de linea",
            "status": "Barra de estado",
            "focus": "Modo enfoque",
        },
        "en": {
            "label": "View",
            "zoom": "Zoom",
            "zoom_in": "Zoom in",
            "zoom_out": "Zoom out",
            "zoom_reset": "Reset zoom",
            "reset_view": "Reset view",
            "zoom_label": "Zoom: {percent}%",
            "wrap": "Line wrap",
            "status": "Status bar",
            "focus": "Focus mode",
        },
        "pt": {
            "label": "Ver",
            "zoom": "Zoom",
            "zoom_in": "Ampliar",
            "zoom_out": "Reduzir",
            "zoom_reset": "Restaurar zoom",
            "reset_view": "Restaurar vista",
            "zoom_label": "Zoom: {percent}%",
            "wrap": "Quebra de linha",
            "status": "Barra de status",
            "focus": "Modo foco",
        },
        "fr": {
            "label": "Affichage",
            "zoom": "Zoom",
            "zoom_in": "Zoom avant",
            "zoom_out": "Zoom arriere",
            "zoom_reset": "Reinitialiser zoom",
            "reset_view": "Reinitialiser vue",
            "zoom_label": "Zoom: {percent}%",
            "wrap": "Retour a la ligne",
            "status": "Barre d'etat",
            "focus": "Mode focus",
        },
    },
    "insert": {
        "es": {
            "label": "Insertar",
            "separator": "Separador",
            "heading": "Encabezado",
            "h1": "Titulo 1 (H1)",
            "h2": "Titulo 2 (H2)",
            "h3": "Titulo 3 (H3)",
            "list": "Lista",
            "bullets": "Lista con vi\u00f1etas",
            "numbered": "Lista numerada",
            "checklist": "Checklist (\u2610 / \u2611)",
            "templates": "Plantillas",
            "quick_note": "Nota rapida",
            "meeting": "Reunion (agenda)",
            "todo": "Pendientes (To-Do)",
            "journal": "Diario",
            "link_code": "Enlaces/Codigo",
            "link": "Enlace",
            "insert_link": "Insertar enlace (URL)",
            "code": "Codigo",
            "code_block": "Bloque de codigo",
            "date": "Fecha",
            "datetime": "Fecha y hora",
        },
        "en": {
            "label": "Insert",
            "separator": "Separator",
            "heading": "Heading",
            "h1": "Title 1 (H1)",
            "h2": "Title 2 (H2)",
            "h3": "Title 3 (H3)",
            "list": "List",
            "bullets": "Bulleted list",
            "numbered": "Numbered list",
            "checklist": "Checklist (\u2610 / \u2611)",
            "templates": "Templates",
            "quick_note": "Quick note",
            "meeting": "Meeting (agenda)",
            "todo": "To-Do",
            "journal": "Journal",
            "link_code": "Links/Code",
            "link": "Link",
            "insert_link": "Insert link (URL)",
            "code": "Code",
            "code_block": "Code block",
            "date": "Date",
            "datetime": "Date and time",
        },
        "pt": {
            "label": "Inserir",
            "separator": "Separador",
            "heading": "Cabecalho",
            "h1": "Titulo 1 (H1)",
            "h2": "Titulo 2 (H2)",
            "h3": "Titulo 3 (H3)",
            "list": "Lista",
            "bullets": "Lista com marcadores",
            "numbered": "Lista numerada",
            "checklist": "Checklist (\u2610 / \u2611)",
            "templates": "Modelos",
            "quick_note": "Nota rapida",
            "meeting": "Reuniao (agenda)",
            "todo": "Pendentes (To-Do)",
            "journal": "Diario",
            "link_code": "Links/Codigo",
            "link": "Link",
            "insert_link": "Inserir link (URL)",
            "code": "Codigo",
            "code_block": "Bloco de codigo",
            "date": "Data",
            "datetime": "Data e hora",
        },
        "fr": {
            "label": "Inserer",
            "separator": "Separateur",
            "heading": "Entete",
            "h1": "Titre 1 (H1)",
            "h2": "Titre 2 (H2)",
            "h3": "Titre 3 (H3)",
            "list": "Liste",
            "bullets": "Liste a puces",
            "numbered": "Liste numerotee",
            "checklist": "Checklist (\u2610 / \u2611)",
            "templates": "Modeles",
            "quick_note": "Note rapide",
            "meeting": "Reunion (agenda)",
            "todo": "A faire (To-Do)",
            "journal": "Journal",
            "link_code": "Liens/Code",
            "link": "Lien",
            "insert_link": "Inserer lien (URL)",
            "code": "Code",
            "code_block": "Bloc de code",
            "date": "Date",
            "datetime": "Date et heure",
        },
    },
    "config": {
        "es": {
            "label": "Configuracion",
            "theme": "Tema",
            "language": "Idioma",
            "templates": "Plantillas",
            "templates_preview": "Vista previa",
            "templates_validate": "Validar",
            "datetime_format": "Formato fecha/hora",
            "date_format": "Formato fecha",
            "open_settings": "Abrir settings",
            "reset_settings": "Restablecer configuracion",
            "warm": "Calido",
            "dark": "Oscuro",
            "minimal": "Minimal",
            "retro": "Retro",
            "lang_es": "Espanol",
            "lang_en": "Ingles",
            "lang_pt": "Portugues",
            "lang_fr": "Frances",
        },
        "en": {
            "label": "Settings",
            "theme": "Theme",
            "language": "Language",
            "templates": "Templates",
            "templates_preview": "Preview",
            "templates_validate": "Validate",
            "datetime_format": "Date/time format",
            "date_format": "Date format",
            "open_settings": "Open settings",
            "reset_settings": "Reset settings",
            "warm": "Warm",
            "dark": "Dark",
            "minimal": "Minimal",
            "retro": "Retro",
            "lang_es": "Spanish",
            "lang_en": "English",
            "lang_pt": "Portuguese",
            "lang_fr": "French",
        },
        "pt": {
            "label": "Configuracao",
            "theme": "Tema",
            "language": "Idioma",
            "templates": "Modelos",
            "templates_preview": "Visualizar",
            "templates_validate": "Validar",
            "datetime_format": "Formato data/hora",
            "date_format": "Formato data",
            "open_settings": "Abrir settings",
            "reset_settings": "Restaurar configuracao",
            "warm": "Quente",
            "dark": "Escuro",
            "minimal": "Minimal",
            "retro": "Retro",
            "lang_es": "Espanhol",
            "lang_en": "Ingles",
            "lang_pt": "Portugues",
            "lang_fr": "Francais",
        },
        "fr": {
            "label": "Parametres",
            "theme": "Theme",
            "language": "Langue",
            "templates": "Modeles",
            "templates_preview": "Apercu",
            "templates_validate": "Valider",
            "datetime_format": "Format date/heure",
            "date_format": "Format de date",
            "open_settings": "Ouvrir settings",
            "reset_settings": "Reinitialiser les parametres",
            "warm": "Chaud",
            "dark": "Sombre",
            "minimal": "Minimal",
            "retro": "Retro",
            "lang_es": "Espagnol",
            "lang_en": "Anglais",
            "lang_pt": "Portugais",
            "lang_fr": "Francais",
        },
    },
    "help": {
        "es": {
            "label": "Ayuda",
            "help": "Ver ayuda",
            "shortcuts": "Atajos",
            "changes": "Novedades",
            "open_readme": "Abrir README",
            "about": "Acerca de",
            "about_with_version": "Acerca de ({version})",
        },
        "en": {
            "label": "Help",
            "help": "View help",
            "shortcuts": "Shortcuts",
            "changes": "Changes",
            "open_readme": "Open README",
            "about": "About",
            "about_with_version": "About ({version})",
        },
        "pt": {
            "label": "Ajuda",
            "help": "Ver ajuda",
            "shortcuts": "Atalhos",
            "changes": "Novidades",
            "open_readme": "Abrir README",
            "about": "Sobre",
            "about_with_version": "Sobre ({version})",
        },
        "fr": {
            "label": "Aide",
            "help": "Voir l'aide",
            "shortcuts": "Raccourcis",
            "changes": "Nouveautes",
            "open_readme": "Ouvrir README",
            "about": "A propos",
            "about_with_version": "A propos ({version})",
        },
    },
}

TOOLBAR_TEXTS = {
    "es": {
        "new": "Nueva",
        "save": "Guardar",
        "saving": "Guardando...",
        "delete": "Borrar",
        "undo": "Deshacer",
        "redo": "Rehacer",
        "cut": "Cortar",
        "copy": "Copiar",
        "paste": "Pegar",
        "bold": "Negrita",
        "italic": "Cursiva",
        "underline": "Subrayado",
        "heading": "Encabezado",
        "list": "Lista",
        "link": "Enlace",
        "date": "Fecha",
        "wrap": "Ajuste",
        "status": "Barra",
        "focus": "Enfoque",
        "zoom_in": "Zoom +",
        "zoom_out": "Zoom -",
        "zoom_reset": "Zoom 100%",
        "more": "Mas",
        "readonly": "Solo lectura",
        "tips": {
            "new": "Nueva nota (Ctrl+N)",
            "save": "Guardar nota (Ctrl+S)",
            "delete": "Borrar nota (Ctrl+Shift+Delete)",
            "undo": "Deshacer (Ctrl+Z)",
            "redo": "Rehacer (Ctrl+Y)",
            "cut": "Cortar seleccion (Ctrl+X)",
            "copy": "Copiar seleccion (Ctrl+C)",
            "paste": "Pegar (Ctrl+V)",
            "bold": "Negrita (Ctrl+B)",
            "italic": "Cursiva (Ctrl+I)",
            "underline": "Subrayado (Ctrl+U)",
            "heading": "Insertar encabezado (Ctrl+Shift+H)",
            "list": "Insertar lista (Ctrl+Shift+L)",
            "link": "Insertar enlace (Ctrl+Alt+U)",
            "date": "Insertar fecha (Ctrl+Shift+D)",
            "wrap": "Ajuste de linea",
            "status": "Barra de estado",
            "focus": "Modo enfoque (Ctrl+Shift+F)",
            "zoom_in": "Aumentar zoom (Ctrl+Alt+Plus)",
            "zoom_out": "Reducir zoom (Ctrl+Alt+Minus)",
            "zoom_reset": "Restablecer zoom (Ctrl+Alt+0)",
        },
    },
    "en": {
        "new": "New",
        "save": "Save",
        "saving": "Saving...",
        "delete": "Delete",
        "undo": "Undo",
        "redo": "Redo",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "bold": "Bold",
        "italic": "Italic",
        "underline": "Underline",
        "heading": "Heading",
        "list": "List",
        "link": "Link",
        "date": "Date",
        "wrap": "Wrap",
        "status": "Status",
        "focus": "Focus",
        "zoom_in": "Zoom +",
        "zoom_out": "Zoom -",
        "zoom_reset": "Zoom 100%",
        "more": "More",
        "readonly": "Read-only",
        "tips": {
            "new": "New note (Ctrl+N)",
            "save": "Save note (Ctrl+S)",
            "delete": "Delete note (Ctrl+Shift+Delete)",
            "undo": "Undo (Ctrl+Z)",
            "redo": "Redo (Ctrl+Y)",
            "cut": "Cut selection (Ctrl+X)",
            "copy": "Copy selection (Ctrl+C)",
            "paste": "Paste (Ctrl+V)",
            "bold": "Bold (Ctrl+B)",
            "italic": "Italic (Ctrl+I)",
            "underline": "Underline (Ctrl+U)",
            "heading": "Insert heading (Ctrl+Shift+H)",
            "list": "Insert list (Ctrl+Shift+L)",
            "link": "Insert link (Ctrl+Alt+U)",
            "date": "Insert date (Ctrl+Shift+D)",
            "wrap": "Line wrap",
            "status": "Status bar",
            "focus": "Focus mode (Ctrl+Shift+F)",
            "zoom_in": "Zoom in (Ctrl+Alt+Plus)",
            "zoom_out": "Zoom out (Ctrl+Alt+Minus)",
            "zoom_reset": "Reset zoom (Ctrl+Alt+0)",
        },
    },
    "pt": {
        "new": "Nova",
        "save": "Salvar",
        "saving": "Salvando...",
        "delete": "Excluir",
        "undo": "Desfazer",
        "redo": "Refazer",
        "cut": "Cortar",
        "copy": "Copiar",
        "paste": "Colar",
        "bold": "Negrito",
        "italic": "Italico",
        "underline": "Sublinhado",
        "heading": "Cabecalho",
        "list": "Lista",
        "link": "Link",
        "date": "Data",
        "wrap": "Quebra",
        "status": "Status",
        "focus": "Foco",
        "zoom_in": "Zoom +",
        "zoom_out": "Zoom -",
        "zoom_reset": "Zoom 100%",
        "more": "Mais",
        "readonly": "Somente leitura",
        "tips": {
            "new": "Nova nota (Ctrl+N)",
            "save": "Salvar nota (Ctrl+S)",
            "delete": "Excluir nota (Ctrl+Shift+Delete)",
            "undo": "Desfazer (Ctrl+Z)",
            "redo": "Refazer (Ctrl+Y)",
            "cut": "Cortar selecao (Ctrl+X)",
            "copy": "Copiar selecao (Ctrl+C)",
            "paste": "Colar (Ctrl+V)",
            "bold": "Negrito (Ctrl+B)",
            "italic": "Italico (Ctrl+I)",
            "underline": "Sublinhado (Ctrl+U)",
            "heading": "Inserir cabecalho (Ctrl+Shift+H)",
            "list": "Inserir lista (Ctrl+Shift+L)",
            "link": "Inserir link (Ctrl+Alt+U)",
            "date": "Inserir data (Ctrl+Shift+D)",
            "wrap": "Quebra de linha",
            "status": "Barra de status",
            "focus": "Modo foco (Ctrl+Shift+F)",
            "zoom_in": "Aumentar zoom (Ctrl+Alt+Plus)",
            "zoom_out": "Diminuir zoom (Ctrl+Alt+Minus)",
            "zoom_reset": "Resetar zoom (Ctrl+Alt+0)",
        },
    },
    "fr": {
        "new": "Nouveau",
        "save": "Enregistrer",
        "saving": "Enregistrement...",
        "delete": "Supprimer",
        "undo": "Annuler",
        "redo": "Retablir",
        "cut": "Couper",
        "copy": "Copier",
        "paste": "Coller",
        "bold": "Gras",
        "italic": "Italique",
        "underline": "Souligner",
        "heading": "Titre",
        "list": "Liste",
        "link": "Lien",
        "date": "Date",
        "wrap": "Retour",
        "status": "Etat",
        "focus": "Focus",
        "zoom_in": "Zoom +",
        "zoom_out": "Zoom -",
        "zoom_reset": "Zoom 100%",
        "more": "Plus",
        "readonly": "Lecture seule",
        "tips": {
            "new": "Nouvelle note (Ctrl+N)",
            "save": "Enregistrer la note (Ctrl+S)",
            "delete": "Supprimer la note (Ctrl+Shift+Delete)",
            "undo": "Annuler (Ctrl+Z)",
            "redo": "Retablir (Ctrl+Y)",
            "cut": "Couper selection (Ctrl+X)",
            "copy": "Copier selection (Ctrl+C)",
            "paste": "Coller (Ctrl+V)",
            "bold": "Gras (Ctrl+B)",
            "italic": "Italique (Ctrl+I)",
            "underline": "Souligner (Ctrl+U)",
            "heading": "Inserer titre (Ctrl+Shift+H)",
            "list": "Inserer liste (Ctrl+Shift+L)",
            "link": "Inserer lien (Ctrl+Alt+U)",
            "date": "Inserer date (Ctrl+Shift+D)",
            "wrap": "Retour a la ligne",
            "status": "Barre d'etat",
            "focus": "Mode focus (Ctrl+Shift+F)",
            "zoom_in": "Zoom avant (Ctrl+Alt+Plus)",
            "zoom_out": "Zoom arriere (Ctrl+Alt+Minus)",
            "zoom_reset": "Reinitialiser zoom (Ctrl+Alt+0)",
        },
    },
}

SIDEBAR_TEXTS = {
    "es": {
        "notes": "Notas",
        "new": "Nueva",
        "delete": "Borrar",
        "sort": "Orden",
        "sort_recent": "Recientes",
        "sort_alpha": "A-Z",
        "sort_pinned": "Pines primero",
        "tags": "Tags",
    },
    "en": {
        "notes": "Notes",
        "new": "New",
        "delete": "Delete",
        "sort": "Sort",
        "sort_recent": "Recent",
        "sort_alpha": "A-Z",
        "sort_pinned": "Pinned first",
        "tags": "Tags",
    },
    "pt": {
        "notes": "Notas",
        "new": "Nova",
        "delete": "Excluir",
        "sort": "Ordenar",
        "sort_recent": "Recentes",
        "sort_alpha": "A-Z",
        "sort_pinned": "Fixados primeiro",
        "tags": "Tags",
    },
    "fr": {
        "notes": "Notes",
        "new": "Nouveau",
        "delete": "Supprimer",
        "sort": "Trier",
        "sort_recent": "Recents",
        "sort_alpha": "A-Z",
        "sort_pinned": "Epingles d'abord",
        "tags": "Tags",
    },
}

DIALOG_TEXTS = {
    "search": {
        "es": {
            "find_title": "Buscar",
            "find_label": "Texto a buscar:",
            "replace_label": "Reemplazar con:",
            "replace_one": "Reemplazar uno",
            "replace_all": "Reemplazar todo",
            "replace_confirm": "Reemplazar todas las coincidencias?",
            "replace_done": "Reemplazos: {count}",
            "next": "Buscar siguiente",
            "prev": "Buscar anterior",
            "not_found": "No se encontro el texto.",
            "match_case": "Coincidir mayusculas",
            "regex": "Regex",
            "whole_word": "Palabra completa",
            "regex_invalid": "Regex invalido.",
        },
        "en": {
            "find_title": "Find",
            "find_label": "Find:",
            "replace_label": "Replace with:",
            "replace_one": "Replace one",
            "replace_all": "Replace all",
            "replace_confirm": "Replace all matches?",
            "replace_done": "Replacements: {count}",
            "next": "Find next",
            "prev": "Find previous",
            "not_found": "Text not found.",
            "match_case": "Match case",
            "regex": "Regex",
            "whole_word": "Whole word",
            "regex_invalid": "Invalid regex.",
        },
        "pt": {
            "find_title": "Buscar",
            "find_label": "Texto a buscar:",
            "replace_label": "Substituir por:",
            "replace_one": "Substituir um",
            "replace_all": "Substituir todos",
            "replace_confirm": "Substituir todas as ocorrencias?",
            "replace_done": "Substituicoes: {count}",
            "next": "Buscar seguinte",
            "prev": "Buscar anterior",
            "not_found": "Texto nao encontrado.",
            "match_case": "Diferenciar maiusculas",
            "regex": "Regex",
            "whole_word": "Palavra inteira",
            "regex_invalid": "Regex invalido.",
        },
        "fr": {
            "find_title": "Rechercher",
            "find_label": "Texte a rechercher:",
            "replace_label": "Remplacer par:",
            "replace_one": "Remplacer un",
            "replace_all": "Tout remplacer",
            "replace_confirm": "Remplacer toutes les occurrences?",
            "replace_done": "Remplacements: {count}",
            "next": "Rechercher suivant",
            "prev": "Rechercher precedent",
            "not_found": "Texte introuvable.",
            "match_case": "Respecter la casse",
            "regex": "Regex",
            "whole_word": "Mot entier",
            "regex_invalid": "Regex invalide.",
        },
    },
    "insert": {
        "es": {
            "dialog_title": "Insertar enlace",
            "url": "URL:",
            "text": "Texto visible:",
            "default_text": "enlace",
        },
        "en": {
            "dialog_title": "Insert link",
            "url": "URL:",
            "text": "Visible text:",
            "default_text": "link",
        },
        "pt": {
            "dialog_title": "Inserir link",
            "url": "URL:",
            "text": "Texto visivel:",
            "default_text": "link",
        },
        "fr": {
            "dialog_title": "Inserer lien",
            "url": "URL:",
            "text": "Texte visible:",
            "default_text": "lien",
        },
    },
    "notes": {
        "es": {
            "delete_title": "Borrar",
            "delete_confirm": "Borrar esta nota?",
            "export_title": "Exportar",
            "export_empty": "No hay nota para exportar.",
            "file_text": "Archivos de texto",
            "file_markdown": "Markdown",
            "unsaved_title": "Guardar cambios",
            "unsaved_message": "Hay cambios sin guardar. Guardar antes de continuar?",
            "error_title": "Error",
            "save_failed": "No se pudo guardar la nota.",
            "load_failed": "No se pudo cargar la nota.",
            "list_failed": "No se pudieron cargar las notas.",
            "delete_failed": "No se pudo borrar la nota.",
            "export_failed": "No se pudo exportar la nota.",
            "import_failed": "No se pudo importar el archivo.",
            "invalid_extension": "Extension invalida. Use {ext}.",
            "change_extension": "El archivo tiene extension diferente. Cambiar a {ext}?",
            "title_prompt": "Titulo de la nota:",
            "placeholder": "Selecciona una nota",
        },
        "en": {
            "delete_title": "Delete",
            "delete_confirm": "Delete this note?",
            "export_title": "Export",
            "export_empty": "There is no note to export.",
            "file_text": "Text files",
            "file_markdown": "Markdown",
            "unsaved_title": "Save changes",
            "unsaved_message": "You have unsaved changes. Save before continuing?",
            "error_title": "Error",
            "save_failed": "Could not save the note.",
            "load_failed": "Could not load the note.",
            "list_failed": "Could not load notes.",
            "delete_failed": "Could not delete the note.",
            "export_failed": "Could not export the note.",
            "import_failed": "Could not import the file.",
            "invalid_extension": "Invalid extension. Use {ext}.",
            "change_extension": "File has a different extension. Change to {ext}?",
            "title_prompt": "Note title:",
            "placeholder": "Select a note",
        },
        "pt": {
            "delete_title": "Excluir",
            "delete_confirm": "Excluir esta nota?",
            "export_title": "Exportar",
            "export_empty": "Nao ha nota para exportar.",
            "file_text": "Arquivos de texto",
            "file_markdown": "Markdown",
            "unsaved_title": "Salvar alteracoes",
            "unsaved_message": "Ha alteracoes nao salvas. Salvar antes de continuar?",
            "error_title": "Erro",
            "save_failed": "Nao foi possivel salvar a nota.",
            "load_failed": "Nao foi possivel carregar a nota.",
            "list_failed": "Nao foi possivel carregar as notas.",
            "delete_failed": "Nao foi possivel excluir a nota.",
            "export_failed": "Nao foi possivel exportar a nota.",
            "import_failed": "Nao foi possivel importar o arquivo.",
            "invalid_extension": "Extensao invalida. Use {ext}.",
            "change_extension": "O arquivo tem outra extensao. Alterar para {ext}?",
            "title_prompt": "Titulo da nota:",
            "placeholder": "Selecione uma nota",
        },
        "fr": {
            "delete_title": "Supprimer",
            "delete_confirm": "Supprimer cette note?",
            "export_title": "Exporter",
            "export_empty": "Aucune note a exporter.",
            "file_text": "Fichiers texte",
            "file_markdown": "Markdown",
            "unsaved_title": "Enregistrer",
            "unsaved_message": "Des modifications non enregistrees. Enregistrer avant de continuer?",
            "error_title": "Erreur",
            "save_failed": "Impossible d'enregistrer la note.",
            "load_failed": "Impossible de charger la note.",
            "list_failed": "Impossible de charger les notes.",
            "delete_failed": "Impossible de supprimer la note.",
            "export_failed": "Impossible d'exporter la note.",
            "import_failed": "Impossible d'importer le fichier.",
            "invalid_extension": "Extension invalide. Utilisez {ext}.",
            "change_extension": "Le fichier a une autre extension. Changer vers {ext}?",
            "title_prompt": "Titre de la note:",
            "placeholder": "Selectionnez une note",
        },
    },
    "templates": {
        "es": {
            "preview_title": "Vista previa de plantillas",
            "validation_title": "Validar plantillas",
            "validation_ok": "Plantillas validas.",
            "validation_errors": "Se encontraron problemas:",
            "origin_label": "Origen",
            "origin_base": "base",
            "origin_override": "override",
            "unknown_key": "Clave desconocida",
            "invalid_value": "Valor invalido",
            "empty_value": "Plantilla vacia",
            "missing_lang": "Sin valor para el idioma actual",
            "open_settings": "Abrir settings.json",
            "settings_missing": "settings.json no encontrado.",
            "settings_open_error": "No se pudo abrir settings.json.",
            "close": "Cerrar",
            "copy_template": "Copiar plantilla",
            "reset_template": "Restaurar defaults",
            "copy_done": "Plantilla copiada al portapapeles.",
            "reset_done": "Se restauro la plantilla.",
        },
        "en": {
            "preview_title": "Template preview",
            "validation_title": "Validate templates",
            "validation_ok": "Templates are valid.",
            "validation_errors": "Issues found:",
            "origin_label": "Origin",
            "origin_base": "base",
            "origin_override": "override",
            "unknown_key": "Unknown key",
            "invalid_value": "Invalid value",
            "empty_value": "Empty template",
            "missing_lang": "Missing value for current language",
            "open_settings": "Open settings.json",
            "settings_missing": "settings.json not found.",
            "settings_open_error": "Could not open settings.json.",
            "close": "Close",
            "copy_template": "Copy template",
            "reset_template": "Restore defaults",
            "copy_done": "Template copied to clipboard.",
            "reset_done": "Template restored.",
        },
        "pt": {
            "preview_title": "Visualizar modelos",
            "validation_title": "Validar modelos",
            "validation_ok": "Modelos validos.",
            "validation_errors": "Problemas encontrados:",
            "origin_label": "Origem",
            "origin_base": "base",
            "origin_override": "override",
            "unknown_key": "Chave desconhecida",
            "invalid_value": "Valor invalido",
            "empty_value": "Modelo vazio",
            "missing_lang": "Sem valor para o idioma atual",
            "open_settings": "Abrir settings.json",
            "settings_missing": "settings.json nao encontrado.",
            "settings_open_error": "Nao foi possivel abrir settings.json.",
            "close": "Fechar",
            "copy_template": "Copiar modelo",
            "reset_template": "Restaurar padrao",
            "copy_done": "Modelo copiado para a area de transferencia.",
            "reset_done": "Modelo restaurado.",
        },
        "fr": {
            "preview_title": "Apercu des modeles",
            "validation_title": "Valider les modeles",
            "validation_ok": "Modeles valides.",
            "validation_errors": "Problemes trouves:",
            "origin_label": "Origine",
            "origin_base": "base",
            "origin_override": "override",
            "unknown_key": "Cle inconnue",
            "invalid_value": "Valeur invalide",
            "empty_value": "Modele vide",
            "missing_lang": "Valeur manquante pour la langue",
            "open_settings": "Ouvrir settings.json",
            "settings_missing": "settings.json introuvable.",
            "settings_open_error": "Impossible d'ouvrir settings.json.",
            "close": "Fermer",
            "copy_template": "Copier le modele",
            "reset_template": "Restaurer les valeurs",
            "copy_done": "Modele copie dans le presse-papiers.",
            "reset_done": "Modele restaure.",
        },
    },
    "config": {
        "es": {
            "date_prompt": "Formato de fecha (strftime):",
            "datetime_prompt": "Formato fecha/hora (strftime):",
            "format_saved": "Formato guardado.",
            "formats_label": "Formatos",
            "format_invalid": "Formato invalido.",
            "open_settings_title": "Configuracion",
            "open_settings_missing": "No existe settings.json. Guarda una configuracion primero.",
            "open_settings_error": "No se pudo abrir settings.json: {error}",
            "reset_title": "Restablecer configuracion",
            "reset_confirm": "Borrar settings.json y restablecer configuracion?",
            "reset_done": "Configuracion restablecida.",
        },
        "en": {
            "date_prompt": "Date format (strftime):",
            "datetime_prompt": "Date/time format (strftime):",
            "format_saved": "Format saved.",
            "formats_label": "Formats",
            "format_invalid": "Invalid format.",
            "open_settings_title": "Settings",
            "open_settings_missing": "settings.json does not exist. Save settings first.",
            "open_settings_error": "Could not open settings.json: {error}",
            "reset_title": "Reset settings",
            "reset_confirm": "Delete settings.json and reset settings?",
            "reset_done": "Settings reset.",
        },
        "pt": {
            "date_prompt": "Formato de data (strftime):",
            "datetime_prompt": "Formato data/hora (strftime):",
            "format_saved": "Formato salvo.",
            "formats_label": "Formatos",
            "format_invalid": "Formato invalido.",
            "open_settings_title": "Configuracao",
            "open_settings_missing": "settings.json nao existe. Salve as configuracoes primeiro.",
            "open_settings_error": "Nao foi possivel abrir settings.json: {error}",
            "reset_title": "Restaurar configuracao",
            "reset_confirm": "Apagar settings.json e restaurar configuracao?",
            "reset_done": "Configuracao restaurada.",
        },
        "fr": {
            "date_prompt": "Format de date (strftime):",
            "datetime_prompt": "Format date/heure (strftime):",
            "format_saved": "Format enregistre.",
            "formats_label": "Formats",
            "format_invalid": "Format invalide.",
            "open_settings_title": "Parametres",
            "open_settings_missing": "settings.json est introuvable. Enregistrez d'abord.",
            "open_settings_error": "Impossible d'ouvrir settings.json: {error}",
            "reset_title": "Reinitialiser les parametres",
            "reset_confirm": "Supprimer settings.json et reinitialiser les parametres?",
            "reset_done": "Parametres reinitialises.",
        },
    },
}

HELP_TEXTS = {
    "es": {
        "help_title": "Ayuda",
        "quick_title": "Ayuda rapida",
        "about_title": "Acerca de",
        "about_body": "Bloc de notas con SQLite y Tkinter.",
        "open_readme": "Abrir README",
        "close": "Cerrar",
        "version_label": "Version",
        "changes_title": "Novedades",
        "readme_missing": "README no encontrado.",
        "readme_open_error": "No se pudo abrir README.",
    },
    "en": {
        "help_title": "Help",
        "quick_title": "Quick help",
        "about_title": "About",
        "about_body": "Notepad with SQLite and Tkinter.",
        "open_readme": "Open README",
        "close": "Close",
        "version_label": "Version",
        "changes_title": "Recent changes",
        "readme_missing": "README not found.",
        "readme_open_error": "Could not open README.",
    },
    "pt": {
        "help_title": "Ajuda",
        "quick_title": "Ajuda rapida",
        "about_title": "Sobre",
        "about_body": "Bloco de notas com SQLite e Tkinter.",
        "open_readme": "Abrir README",
        "close": "Fechar",
        "version_label": "Versao",
        "changes_title": "Novidades",
        "readme_missing": "README nao encontrado.",
        "readme_open_error": "Nao foi possivel abrir README.",
    },
    "fr": {
        "help_title": "Aide",
        "quick_title": "Aide rapide",
        "about_title": "A propos",
        "about_body": "Bloc-notes avec SQLite et Tkinter.",
        "open_readme": "Ouvrir README",
        "close": "Fermer",
        "version_label": "Version",
        "changes_title": "Nouveautes",
        "readme_missing": "README introuvable.",
        "readme_open_error": "Impossible d'ouvrir README.",
    },
}

HELP_CHANGES = {
    "es": [
        "v0.4.0 Menus y dialogs multilenguaje",
        "v0.4.0 Ayuda dinamica y formateo mejorado",
    ],
    "en": [
        "v0.4.0 Multilingual menus and dialogs",
        "v0.4.0 Dynamic help and improved formatting",
    ],
    "pt": [
        "v0.4.0 Menus e dialogs multilenguaje",
        "v0.4.0 Ajuda dinamica e formatacao melhorada",
    ],
    "fr": [
        "v0.4.0 Menus et dialogs multilingues",
        "v0.4.0 Aide dynamique et formatage ameliore",
    ],
}

STATUS_TEXTS = {
    "es": {
        "line": "Linea",
        "col": "Col",
        "sel": "Sel",
        "lines": "Lineas",
        "words": "Palabras",
        "chars": "Caracteres",
        "zoom": "Zoom",
        "saved": "Guardado",
        "unsaved": "Cambios sin guardar",
        "saving": "Guardando...",
        "focus": "Enfoque",
        "readonly": "Solo lectura",
        "matches": "Coincidencias",
        "config": "Config",
    },
    "en": {
        "line": "Ln",
        "col": "Col",
        "sel": "Sel",
        "lines": "Lines",
        "words": "Words",
        "chars": "Chars",
        "zoom": "Zoom",
        "saved": "Saved",
        "unsaved": "Unsaved changes",
        "saving": "Saving...",
        "focus": "Focus",
        "readonly": "Read-only",
        "matches": "Matches",
        "config": "Config",
    },
    "pt": {
        "line": "Linha",
        "col": "Col",
        "sel": "Sel",
        "lines": "Linhas",
        "words": "Palavras",
        "chars": "Caracteres",
        "zoom": "Zoom",
        "saved": "Salvo",
        "unsaved": "Alteracoes nao salvas",
        "saving": "Salvando...",
        "focus": "Foco",
        "readonly": "Somente leitura",
        "matches": "Correspondencias",
        "config": "Config",
    },
    "fr": {
        "line": "Ligne",
        "col": "Col",
        "sel": "Sel",
        "lines": "Lignes",
        "words": "Mots",
        "chars": "Caracteres",
        "zoom": "Zoom",
        "saved": "Enregistre",
        "unsaved": "Modifications non enregistrees",
        "saving": "Enregistrement...",
        "focus": "Focus",
        "readonly": "Lecture seule",
        "matches": "Correspondances",
        "config": "Config",
    },
}

INSERT_TEMPLATES = {
    "es": {
        "separator": "\n---\n",
        "heading": "\n## Encabezado\n",
        "h1": "\n# Titulo 1\n",
        "h2": "\n## Titulo 2\n",
        "h3": "\n### Titulo 3\n",
        "list": "\nItem 1\nItem 2\n",
        "bullets": "\n\u2022 Item 1\n\u2022 Item 2\n",
        "numbered": "\n1. Item 1\n2. Item 2\n",
        "checklist": "\n\u2610 Tarea 1\n\u2610 Tarea 2\n\u2611 Tarea hecha\n",
        "quick_note": "\n# Nota rapida\n\nContexto:\n\nIdea:\n\nProximos pasos:\n",
        "meeting": (
            "\n# Reunion\n\nFecha:\nParticipantes:\n\nAgenda:\n- \n\nNotas:\n- \n\n"
            "Acciones:\n- [ ] \n"
        ),
        "todo": (
            "\n# Pendientes\n\nPrioridad alta:\n- [ ] \n\nPendientes:\n- [ ] "
            "\n\nHecho:\n- [x] \n"
        ),
        "journal": "\n# Diario\n\nFecha:\n\nEstado de animo:\n\nNotas:\n\nAprendizajes:\n",
        "link_template": "[texto](https://)",
        "inline_code": "`codigo`",
        "code_block": "\n```\ncodigo\n```\n",
    }
}
